include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_use_of_protected_member: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
  #    sort_pub_dependencies: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_specify_types: false
    avoid_classes_with_only_static_members: false
    avoid_print: false
    lines_longer_than_80_chars: true
    prefer_single_quotes: true
    prefer_double_quotes: false
    public_member_api_docs: false
    sort_constructors_first: true
